apiVersion: v1
kind: Service
metadata:
  name: booking
  labels:
    app: booking
    service: booking
spec:
  selector:
    app: booking
  ports:
  - port: 9001
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiosample-booking
  labels:
    account: booking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
    version: v1
spec:
  selector:
    matchLabels:
      app: booking
      version: v1
  template:
    metadata:
      labels:
        app: booking
        version: v1
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      containers:
      - name: booking
        image: southouse/istio-sample-booking
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP